Replace capability dictionary with str.lower()
The "cap" dictionary didn't bring any value and needed to be updated
with new capabilities.

Fixes:
        Udica fails when container info contains CAP_PERFMON
        Couldn't create policy: 'PERFMON'
        Error: Process completed with exit code 4.

        https://github.com/containers/udica/issues/88

Signed-off-by: Vit Mojzis <vmojzis@redhat.com>